# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('.env', '.'),
        ('web.config', '.'),
        ('Module_Router.txt', '.'),
        ('SLA_SERVICE_README.md', '.'),
        ('requirements.txt', '.'),
        ('models', 'models'),
        ('routers', 'routers'),
        ('services', 'services'),
        ('data', 'data'),
        ('logs', 'logs'),
        ('tests', 'tests'),
        ('scratch', 'scratch'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'models',
        'models.schemas',
        'routers',
        'routers.auth',
        'routers.chat',
        'routers.sla',
        'routers.tickets',
        'services',
        'services.chat_service',
        'services.sla_monitor_service',
        'services.sla_reminder_store',
        'services.sla_scheduler',
        'services.ticket_creator_service',
        'query_engine',
        'ams_api',
        'config',
        'Module_Router',
        'ticket_filter',
        'run_scheduler',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['pyi_env_hook.py'],
    excludes=[
        'venv',
        '.venv',
        '__pycache__',
        'build',
        'dist',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ams_backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
